config/routes.rb
Rails.application.routes.draw do	
  devise_for :users
  root to: "pages#home"
  get 'dashboard', to: "pages#dashboard"
  get 'proposition', to: "pages#proposition"
  get 'member', to: "pages#member"
  resources :events
  resources :events_users, only: [:destroy, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  #authenticate :user -> (user) {user.admin?} do
  mount Sidekiq::Web => '/sidekiq'
  #end
  	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  def self.search(search)
  	if search
  		
  		events = Event.where(theme: search, visible: true)

  		if events.count > 0
  			Event.where(theme: search, visible: true)
  		else
  			Event.where(visible: true)	

  		end
  		
  	else
  		self.where(visible: true)
  	end
  end

end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_params, if: :devise_controller?

	 def configure_permitted_params
	 	devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :admin])
	 end

    include Pundit

	after_action :verify_authorized , except: :index, unless: :skip_pundit?
	after_action :verify_policy_scoped , only: :index, unless: :skip_pundit?

	private

	def skip_pundit?
		devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    skip_before_action :authenticate_user!, only: :index
	before_action :set_event , only: [:show, :edit, :update, :destroy]

    def index
        @events = policy_scope(Event.search(params[:search]))
    end

    def new
    	@event = Event.new
    	authorize @event
    end
    def show
        
    end
    def create
    	@event = Event.new(event_params)
    	authorize @event
    	@event.user = current_user

    	if @event.save
    		redirect_to new_event_path , notice: "Votre événement sera examiné par un Admin avant sa publication, un mail vous sera envoyé par la suite."
		else
    		render 'new'
    	end
    end

    def edit    	
    end

    def update
        before = @event.visible
    	@event.update(event_params)
        after = @event.visible
        if !before && after
            message = "Felicitation, votre evenement vient d'être accepter et publier sur notre site."
            MailerJob.perform_later(@event.user, message)
            # SendMailer.with(user: @event.user, message: message).submission.deliver_later
        end
    	redirect_to event_path(@event)
    end

    def destroy
        message = "Votre evenement à été rejeté car il n'est pas conforme avec notre politique d'utilisation."
        if !@event.visible?
            MailerJob.perform_later(@event.user, message)
            # SendMailer.with(user: @event.user, message: message).submission.deliver_later
        end
        EventsUser.where(event_id: @event.id).destroy_all
        @event.destroy
      
        if current_user.admin?
          redirect_to proposition_path

        else
            redirect_to events_path
        end
    end

    private
    def set_event
    	@event = Event.find(params[:id])
    	authorize @event
    end

    private 
    def event_params
    	params.require(:event).permit(:name, :adress, :theme, :description, :date, :photo, :visible, :search)
    end
end

app/controllers/events_users_controller.rb
class EventsUsersController < ApplicationController


	def create
    	@participe = EventsUser.new(:event_id => params[:event_id], :user_id => params[:user_id])
    	authorize @participe.event
    	if @participe.save
    		redirect_to event_path(@participe.event)
		else
    		redirect_to event_path(@participe.event)
    	end
    end
    def destroy
    	@participe = EventsUser.find(params[:id])
    	@event = @participe.event
    	authorize @event
		@participe.destroy
		redirect_to event_path(@event)
	end
    def set_restaurant
		@participe = EventsUser.find(params[:id])
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @events = policy_scope(Event.search(nil))
  end

  def dashboard
    @user = current_user
  end

  def proposition

    if current_user.admin?
      @events = Event.where(visible: nil)
    else
      redirect_to root_path, notice: "Vous n'avez pas l'autorisation requise pour acceder à cette page"
    end
  	
  end
  def member
    
    if current_user.admin?
      @users = User.where(admin: nil)
    else
      redirect_to root_path, notice: "Vous n'avez pas l'autorisation requise pour acceder à cette page"
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/events_users_helper.rb
module EventsUsersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= simple_form_for @event do |f| %>

	<%= f.input :name%>
	<%= f.input :adress%>
	<%= f.input :theme%>
	<%= f.input :description%>
	<%= f.input :date%>
	<%= f.input :photo, as: :file%>
	<%= f.submit %>
	
<% end %>

app/views/events/index.html.erb
<div class="container" style="margin-top: 5%;">
      <div class="row justify-content-md-center">
       
        </div>
      </div>
    <% @events.each do |event| %>
    <div class='cadre mx-auto bg-white shadow mb-5'>
              <a class='lienEvent' href='/events/<%= event.id %>'>
                <div class='container mw-100'>
                  <div class='row'>
                    <div class='col-sm-6 p-0' style='height: 400px;'>
                      <% if event.photo.attached? %>

                        <%= cl_image_tag(event.photo.key, width:'100%', height: '100%' ) %>
                      <% end %>
                    </div>
                    <div class='col-sm-6 p-5'>
                      <p><%= event.date %></p>
                      <h3><%= event.name %></h3>
                      <br/>
                      <h5>Localisation : <%= event.adress %></h5> <br/>
                      <h5>Thème : <%= event.theme %> </h5><br/>
                      <h5>Nombre de participants : <%= EventsUser.where(event_id: event.id).count %></h5>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          <% end %>  

app/views/events/new.html.erb
<%= simple_form_for @event do |f| %>
	<div align="center">
		<h1>New Event</h1>
		<label>Name</label>
		<div class="form-group col-md-7">
	<%= f.text_field :name , as: :text , :input_html => { :rows => 2 , :style => 'width: 100%'}, required: true %>
	</div>
	<label>Adress</label>
	<div class="form-group col-sm-7">
	<%= f.text_field :adress, as: :text , :input_html => { :rows => 2 , :style => 'width: 100%'}, required: true, class: "form-control" %>
	</div>

	<div class="form-group col-md-6">
		<label>Theme</label>
		<select class="form-select" aria-label="Default select example"  name="event[theme]" id="event_theme">
		  <option>Caritatif</option>
		  <option>Concert</option>
		  <option>Étudiant</option>
		  <option>Showcase</option>
		  <option>Sport</option>
		  <option>Festival</option>
		  <option>Randonée</option>
		  <option>Orchestre / Musique</option>
		  <option>Football</option>
		  <option>Chasse au trésor</option>
		  <option>Shooting photo</option>
		  <option>Jeux vidéos</option>
		  <option>Conférence</option>
		  <option>Cinéma</option>
		  <option>Pool Party</option>
		</select>
	</div>
	<div class="form-group col-sm-6" align="center" >
		<label>Description</label>
		<textarea class="form-control" name="event[description]" id="event_description" rows="3"></textarea>
	</div>
<div class="form-group col-md-4">
	<label>Date & Heure</label><br>
	<%= f.datetime_field :date, :input_html => { :rows => 2 , :style => 'width: 100%'}, required: true%>
</div>
<br>
<div class="form-group col-md-4">
	<%= f.file_field :photo, as: :file, accept:'image/*', :input_html => { :rows => 2 , :style => 'width: 100%'}, required: false %>
</div>
<br>
<div class="form-group col-md-4">
	<%= f.submit %>
	</div>
	
<% end %>

app/views/events/show.html.erb
<div class="flou">
	<div id="fb-root"></div>

		<div class='flou'>
			<div class='cadre mx-auto bg-white shadow mb-5'>
				<div class='container mw-100 border-bottom border-dark'>
					<div class='row'>
						<div class='col-sm-8 p-0' style='height: 450px;'>
							<% if @event.photo.attached? %>

								<%= cl_image_tag(@event.photo.key, width:'100%', height: '100%' ) %>
							<% end %>	
						</div>
						<div class='col-sm-4 p-5'>

							<p><%= @event.date %></p>

							<%= @participe %>
							<h3><%= @event.name %></h3>
							<br/>
							<h5>Localisation : <%= @event.adress %></h5> <br/>
							<h5>Thème : <%= @event.theme %> </h5><br/>
							<h5>Nombre de participants : <%= EventsUser.where(event_id: @event.id).count %></h5>
							<br/><br/>
						</div>
					</div>
				</div>

				<div class='p-2 container mw-100 border-bottom border-dark'>
					<div class='row'>
						<div class='col'>


						</div>
						
						<div class='col-md-auto'>

							<% if user_signed_in?  && current_user.admin && !@event.visible?%>
							<%= link_to "Accepter l'évenement", event_path(:event =>
																			  {:name => @event.name,
																			   :adress => @event.adress,
																			   :theme => @event.theme,
																			   :description => @event.description,
																			   :date => @event.date,
																			   :visible => true,
																			 :id => @event.id}), :method => :put, class: 'btn btn-success', id: 'parti' %>
							<% end %>

							<% if user_signed_in?  && current_user.admin %>
							<%= link_to @event.visible ? "Supprimer l'évenement" : "Rejetter l'évenement" , event_path(@event.id), :method => 
							:delete, class: 'btn btn-danger', id: 'parti' %>
							<% end %>

							<% if !current_user.admin %>

								<% if EventsUser.find_by(event_id: @event.id, user_id: current_user.id)%>
									<%= link_to "Ne plus participer à l'évenement", events_user_path(EventsUser.find_by(event_id: @event.id, user_id: current_user.id)),:method => :delete, class: 'btn btn-danger', id: 'parti' %>
								<%end%>

								<% if !EventsUser.find_by(event_id: @event.id, user_id: current_user.id)%>
								<%= link_to "Participer à l'évenement", events_users_path(:event_id => @event.id, :user_id => current_user.id), 
								:method => :post, class: 'btn btn-success', id: 'parti' %>
								<%end%>
								
							<%end %>
							

							</form>
						</div>
					</div>
				</div>

				
				<div class='p-3'>
					<h6>Description :</h6>
					<%= @event.description %>
					<br/><br/>
				</div>
			</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NearbyEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
                                            <!-- header -->
    <header  id='header' class='fixed-top'>
      <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
        <div class="container-fluid">
          <%= link_to 'Nearby-Events', root_path , class: 'navbar-brand'%>
          <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
          </button>

          <div class='collapse navbar-collapse' id='navbarSupportedContent'>
            <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
              <li class='nav-item active'>
                <%= link_to 'Home', root_path , class: 'nav-link'%>
              </li>
              <li class='nav-item'>
                <%= link_to 'Events', events_path , class: 'nav-link'%>
              </li>
              <% if user_signed_in?  && current_user.admin %>
                <li class='nav-item'>
                  <%= link_to 'Propositions('+ String(Event.where(visible: nil).count) +')', proposition_path , class: 'nav-link'%>
                </li>
                <li class='nav-item'>
                  <%= link_to 'Users('+ String(User.where(admin: nil).count) +')', member_path , class: 'nav-link'%>
                </li>
              <% end %>
              <% if user_signed_in?  && !current_user.admin %>
                <%= link_to "Add Event", new_event_path, class: 'nav-link' %>
              <% end %>
            </ul>

            <div class="d-flex justify-content-end">
              <form action="/events" method="get" class="barre">
                <input type="search" class="search" placeholder="Search by theme" name="search" required>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 -1 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
              </svg>
          </form>
            </div>
              <form class="d-flex" >
                <div class="d-flex justify-content-end">


                  <% if user_signed_in? %>
                    
                  <a id='profil' class='nav-link text-light' href="/users/edit">
                    <svg id='usericon' width='32' height='32' viewBox='0 0 20 20' fill='currentColor' >
                      <path fill-rule='evenodd' d='M5 16s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H5zm5-6a3 3 0 100-6 3 3 0 000 6z' clip-rule='evenodd'/>
                    </svg>

                    <span id='txticon'><%= current_user.first_name %></span>

                  </a>
                  <% end %>

                  <%= link_to 'Sign in', new_user_session_path, id: 'ik',class: 'btn btn-primary btn-light' unless user_signed_in? %>
                  <%= link_to 'Sign up', new_user_registration_path, id: 'ik', class: 'btn btn-primary btn-info mr-2', style: "background-color: #68AFB8" unless user_signed_in? %>
                  <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-primary btn-success', method: :delete if user_signed_in? %>
                </div>
              </form>
          </div>
        </div>
      </nav>
    </header>
    <h1> &nbsp; </h1>
      <% flash.each do |type, msg| %>
      <div align="center" class="alert alert-info">
        <%= msg %>
      </div>
      <% end %>
    <%= yield %>
                                             
    <footer class="container-fluid text-center border-top mt-5 text-black-50 bg-white pb-0 shadow">

          <div class="copyrights row" style="margin-top:25px;">
              <p>Neaby-Events © 2021, All Rights Reserved
                  <br>
                  <span>Created and Designed By : Dassoukhi Saleh</span></p>
              <p class="mb-0"><a href="https://www.linkedin.com/in/dassoukhi-saleh-823aa412a" target="_blank">LinkedIn<i class="fa fa-linkedin-square" ></i> </a></p>
          </div>
  </footer>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Bienvenue <%= @user.first_name.capitalize if @user.first_name %> sur ton dashboard</h1>

<p>Votre email : <%= @user.email %></p>

app/views/pages/home.html.erb
<div id='myCarousel' class='carousel slide' data-ride='carousel'>



<div class="carousel-inner">
	<div class="carousel-item active">
		 <%= image_tag("comedie3.jpg") %>
		<div class="container">
			<div class="carousel-caption d-none d-md-block text-left">
				<p>Let's live together through wonderful events</p>
				<p></p>
				
			</div>
		</div>
	</div>

</div>

</div>
	<div class='container'>
		<div id='contribEvent' class='row'>
		<% @events.each do |event| %>
		<div class='col-sm-3 col-md-3 p-0 mx-0'style='height:25%'>
			<a class='lienEvent' href='/events/<%= event.id %>'>
			   	 <div class="card" style="width: 18rem;">
			        <%= cl_image_tag(event.photo.key, width:'100%', height: '150px' ) %>
				  <div class="card-body">
				  	<p class="card-text"><%= event.date %></p>
				  	<h6 class="card-title"><%= event.name %></h6>
				    <p class="card-text"><%= event.adress %></p>
				  </div>
				</div>
			</a>
		</div>
		<% end %>
	</div>
</div>

app/views/pages/member.html.erb
<form method='post'>
	<div class='cadre mx-auto bg-white shadow mb-5'>
		<div class='container mw-100'>
			<div class='row p-3'>
				<% @users.each do |user| %>
				<div class='col-sm-3 col-md-2 border p-2 m-auto' style='height:75%'>
					<h4><%= user.first_name %></h4>
					<p><%= user.last_name %></p>
					<p><%= user.email %></p>
					<%= link_to "Supprimer cet utilisateur", user_registration_path(user), :method => :delete, class: 'btn btn-outline-danger' %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</form>

app/views/pages/proposition.html.erb
<%if @events.length == 0 %>
	<div align="center">
		<h2>Aucun nouveau Event</h2>
	</div>
<% end %>


<% @events.each do |event| %>

	<a class='lienEvent' href='/events/<%= event.id %>'>
		<div class='cadre mx-auto bg-white shadow mb-5'>
				<div class='container mw-100'>
					<div class='row'>
						<div class='col-sm-6 p-0' style="height: 400px">
						<% if event.photo.attached? %>

                        	<%= cl_image_tag(event.photo.key, width:'100%', height: '100%' ) %>
                     	 <% end %>						
                     	</div>
						<div class='col-sm-6 p-5'>
							 <p><%= event.date %></p>
		                      <h3><%= event.name %></h3>
		                      <br/>
		                      <h5>Localisation : <%= event.adress %></h5> <br/>
		                      <h5>Thème : <%= event.theme %> </h5><br/>
		                      <h5>Nombre de participants : <%= EventsUser.where(event_id: event.id).count %></h5>
						</div>
					</div>
				</div>
		</div>
	</a>

<% end %>  